---
- name: Playbook - Back
  hosts: localhost
  become: true
  tasks:
      - name: Install inital programs
        apt: name={{ item }} state=installed
        with_items:
          - nginx
          - npm
          - git
          - node
          - nodejs

      - name: install mysql     
        apt: name=mysql update_cache=yes cache_valid_time=3600 state=present
      
      - name: start up the mysql service  
        shell: "service mysql start"  

      - name: ensure mysql is enabled to run on startup  
        service: name=mysql state=started enabled=true
      
      - name: create database  
        mysql_db: name=movie_db state=present login_user=admin login_password="{{ mysql_admin_password }}"   

      - name: insert data into database  
        mysql_db: name=movie_db state=import target=/home/ubuntu/repos/movie-analyst-api/data_model/table_creation_and_inserts.sql
                  login_user=admin login_password="{{ mysql_admin_password }}"
        
      - name: Clone github repository
        git:
          repo: https://github.com/carlosandrescardenas/movie-analyst-api.git
          dest: /home/ubuntu/repos
          clone: yes
          update: yes
      
      - name: install NPM
        shell: npm i
        args:
          chdir: /home/ubuntu/repos/movie-analyst-api


#echo export DB_HOST=${endpoint} | sudo tee -a /etc/environment
#echo export DB_USER=admin | sudo tee -a /etc/environment
#echo export DB_PASS=rampuptest2021 | sudo tee -a /etc/environment
#echo export DB_NAME=movie_db | sudo tee -a /etc/environment
#cd /movie-analyst-api/
#node server.js